# Generated by Django 4.2.3 on 2023-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_receta_imagen_alter_proveedor_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='receta',
            name='imagen_url',
            field=models.CharField(default='hola', max_length=200),
            preserve_default=False,
        ),
    ]
