# Generated by Django 4.2.3 on 2023-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_receta_imagen_receta_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen_url',
            field=models.CharField(max_length=2000),
        ),
    ]
