# Generated by Django 4.2.3 on 2023-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_receta_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocinero',
            name='anios_experiencia',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocinero',
            name='email',
            field=models.CharField(default='fedekrenn@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocinero',
            name='telefono',
            field=models.CharField(default=3512367758, max_length=50),
            preserve_default=False,
        ),
    ]
