# Generated by Django 5.2.17 on 2026-08-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen_url',
            field=models.URLField(max_length=2000),
        ),
    ]
