# Generated by Django 5.2.17 on 2026-08-19 02:18

from django.db import migrations


def asignar_propietario_legado(apps, schema_editor):
    User = apps.get_model("auth", "User")
    superusuario = User.objects.filter(is_superuser=True).order_by("id").first()
    if superusuario is None:
        return

    for nombre_modelo in ("Cocinero", "Proveedor", "Receta", "Restaurante"):
        Modelo = apps.get_model("aplicacion", nombre_modelo)
        Modelo.objects.filter(propietario__isnull=True).update(
            propietario=superusuario
        )


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_cocinero_propietario_proveedor_propietario_and_more'),
    ]

    operations = [
        migrations.RunPython(asignar_propietario_legado, revertir),
    ]
